name: 'proxy'
type: 'nodejs:14'

web:
  commands:
    # This is roughly the same command found in `npm run start`. It's repeated
    # here because of respawning issues when using `npm run start`. See
    # https://docs.platform.sh/languages/nodejs.html#configuration
    start: "/app/ilr_proxy-submodule/node_modules/.bin/pm2 start /app/ilr_proxy-submodule/server.js -i 4 --no-daemon --max-memory-restart 200M --name 'web-proxy'"

hooks:
  build: |
    if [ ! -z "$AWS_ACCESS_KEY_ID" ] && [ ! -z "$AWS_SECRET_ACCESS_KEY" ]; then
      pip install futures
      pip install awscli --upgrade --user 2>/dev/null
    fi
    set -e
    cd ilr_proxy-submodule
    npm install --production

mounts:
  run:
    source: local
    source_path: run
  tmp:
    source: local
    source_path: tmp

disk: 512

crons:
  upload_logs_to_s3:
    # This is run hourly at 54 minutes after the hour, since platform.sh can
    # delay cron runs by up to 300 seconds.
    spec: '54 * * * *'
    cmd: |
      if [ "$PLATFORM_BRANCH" = master ]; then
        bash bin/upload_logs_to_s3.sh
      fi
