drupal8:
  type: 'php:8.3'
  source:
    root: drupal

  relationships:
    database: 'db:mysql'
    reports: 'db:reporter'

  runtime:
    extensions:
      - imagick
      - apcu
      - sodium
    # Help platform better calculate the number of PHP-FPM workers available.
    # See https://docs.platform.sh/languages/php/fpm.html
    sizing_hints:
      request_memory: 110
      reserved_memory: 110
    xdebug:
      idekey: ILR_WEBTEAM_DEBUG

  variables:
    php:
      display_errors: Off
      display_startup_errors: Off
      upload_max_filesize: 128M
      post_max_size: 128M

  # 1024 * 42.5
  disk: 43520

  size: L
  resources:
    base_memory: 1024
    memory_ratio: 512
    # Memory allocation: 1024 + (2 * 512) = 2048

  # The 'mounts' describe writable, persistent filesystem mounts in the application.
  mounts:
    '/web/sites/default/files-d8':
        source: local
        source_path: 'files-d8'
    '/private':
        source: local
        source_path: 'private'
    '/tmp':
        source: local
        source_path: 'tmp'
    '/.drush':
        source: local
        source_path: 'drush'
    '/drush-backups':
        source: local
        source_path: 'drush-backups'
    '/.console':
        source: local
        source_path: 'console'
    '/data':
        source: local
        source_path: 'data'

  # Configuration of the build of this application.
  build:
    flavor: none

  dependencies:
    php:
      composer/composer: '^2.0'

  # The hooks executed at various points in the lifecycle of the application.
  hooks:
    build: |
      set -e
      echo "IyBTZWUgaHR0cHM6Ly9kb2NzLnBsYXRmb3JtLnNoL2d1aWRlcy9kcnVwYWw5L2RlcGxveS9jdXN0b21pemUuaHRtbCNlbnZpcm9ubWVudAppZiBbIC1uICIkUExBVEZPUk1fQVBQX0RJUiIgLWEgLWYgIiRQTEFURk9STV9BUFBfRElSIi9jb21wb3Nlci5qc29uIF0gOyB0aGVuCiAgYmluPSQoY29tcG9zZXIgY29uZmlnIGJpbi1kaXIgLS13b3JraW5nLWRpcj0iJFBMQVRGT1JNX0FQUF9ESVIiIC0tbm8taW50ZXJhY3Rpb24gMj4vZGV2L251bGwpCiAgZXhwb3J0IFBBVEg9IiR7UExBVEZPUk1fQVBQX0RJUn0vJHtiaW46LXZlbmRvci9iaW59OiR7UEFUSH0iCmZp" | base64 -d - > .environment
      curl -sS https://platform.sh/cli/installer | php
      composer --no-dev --no-ansi --no-interaction install --no-progress --prefer-dist --optimize-autoloader
      npm install
      npm run build
    deploy: |
      set -e
      curl -sS https://raw.githubusercontent.com/ilrWebServices/platformsh/8fd5d3/platformsh_generate_drush_yml.php | php > ~/.drush/drush.yml
      drush deploy
      drush locale:update

  web:
    locations:
      '/':
        root: 'web'

        # How long to allow static assets from this location to be cached.
        #
        # Can be a time in seconds, or -1 for no caching. Times can be
        # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
        # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
        # 365 days).
        expires: 1d

        # Whether to forward disallowed and missing resources from this
        # location to the application.
        #
        # Can be true, false or a URI path string.
        passthru: '/index.php'

        # Deny access to static files in this location.
        allow: false

        # Rules for specific URI patterns.
        rules:
          # Allow access to common static files.
          '(?i)\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf|pdf|docx?|mp3|json)$':
            allow: true
          '^/robots\.txt$':
            allow: true
          '^/sitemap\.xml$':
            allow: true

          # Deny direct access to configuration files.
          '^/sites/sites\.php$':
            scripts: false
          '^/sites/[^/]+/settings.*?\.php$':
            scripts: false

      '/sites/default/files-d8':
        # Allow access to all files in the public files directory.
        allow: true
        expires: 5m
        passthru: '/index.php'
        root: 'web/sites/default/files-d8'

        # Do not execute PHP scripts.
        scripts: false

        rules:
          # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
          '^/sites/default/files-d8/(css|js)':
            expires: 2w

  # Set the timezone for cron jobs.
  timezone: "America/New_York"

  # The configuration of scheduled execution.
  crons:
    drupal:
      # Run drush cron every hour
      spec: '0 * * * *'
      cmd: 'drush core-cron'
    collegenet-import:
      # Run CollegeNET importer every day at 7:05 and 12:05.
      spec: '5 7,12 * * *'
      cmd: 'drush collegenet2sf:run'
    database-log-vacuum:
      # Vacuum the dblog database every day at 11pm.
      spec: '0 23 * * *'
      cmd: 'echo "VACUUM;" | sqlite3 /app/data/dblog.sqlite'
    grist-link-log-cleanup:
      # Run script to remove old entries from the Grist link log db @ 10pm every Friday.
      spec: '0 22 * * 5'
      cmd: 'php /app/scripts/grist_link_log_purge.php'
proxy:
  type: 'golang:1.23'
  source:
    root: proxy

  variables:
    env:
      # Set some non-sensitive log backup variables.
      LOGS_S3_BUCKET: "ilrweb-logs"
      LOGS_S3_FOLDER: "platform-logs"
      LOGS_TMP_PATH: "/app/tmp"

  web:
    upstream:
      socket_family: tcp
      protocol: http
    commands:
      start: ./bin/app
    locations:
      /:
        # Route all requests to the Go proxy app, unconditionally.
        allow: false
        passthru: true

  hooks:
    build: |
      set -e

      go build -o bin/app

      if [ ! -z "$AWS_ACCESS_KEY_ID" ] && [ ! -z "$AWS_SECRET_ACCESS_KEY" ]; then
        pip install futures
        pip install awscli --upgrade --user 2>/dev/null
      fi

      echo "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKIyBUaGlzIHNjcmlwdCBpcyBpbnRlbmRlZCB0byBydW4gdmlhIGNyb24gb24gcGxhdGZvcm0uc2gKIyBGcm9tIGh0dHBzOi8vZ2l0bGFiLmNvbS9jb250ZXh0dWFsY29kZS9wbGF0Zm9ybXNoLXN0b3JlLWxvZ3MtYXQtczMKCiMgQ29uZmlndXJlZCB2aWEgZW52aXJvbm1lbnQgdmFyaWFibGVzLiBTZW5zaXRpdmUgdmFycyBhcmUgc2V0IG9uIHBsYXRmb3JtOgojIHBsYXRmb3JtIHZhcmlhYmxlOmNyZWF0ZSAtLWxldmVsPXByb2plY3QgLS1uYW1lPUFXU19BQ0NFU1NfS0VZX0lEIC0tdmFsdWU9PEtFWV9JRD4gLS1qc29uPWZhbHNlIC0tc2Vuc2l0aXZlPXRydWUgLS1wcmVmaXg9ZW52IC0tdmlzaWJsZS1idWlsZD10cnVlIC0tdmlzaWJsZS1ydW50aW1lPXRydWUKIyBwbGF0Zm9ybSB2YXJpYWJsZTpjcmVhdGUgLS1sZXZlbD1wcm9qZWN0IC0tbmFtZT1BV1NfU0VDUkVUX0FDQ0VTU19LRVkgLS12YWx1ZT08QUNDRVNTX0tFWT4gLS1qc29uPWZhbHNlIC0tc2Vuc2l0aXZlPXRydWUgLS1wcmVmaXg9ZW52IC0tdmlzaWJsZS1idWlsZD10cnVlIC0tdmlzaWJsZS1ydW50aW1lPXRydWUKCiMgTm9uLXNlbnNpdGl2ZSB2YXJzIGFyZSBzZXQgaW4gLi4vLmVudmlyb25tZW50LgoKY2QgJExPR1NfVE1QX1BBVEgKVE9EQVlfREFURT0kKGRhdGUgKyVZLSVtLSVkKQoKIyBUaGlzIGlzIHRoZSBuYW1lIG9mIHRoZSBsb2cgZmlsZSBmb3IgYSBnaXZlbiBkYXkuCkxPR19GSUxFPSR7UExBVEZPUk1fUFJPSkVDVH0tJHtQTEFURk9STV9BUFBMSUNBVElPTl9OQU1FfS0ke1RPREFZX0RBVEV9LWFjY2Vzcy5sb2cKCiMgQ29weSB0aGUgbG9nIGZpbGUgZnJvbSBTMy4KYXdzIHMzIGNwIHMzOi8vJHtMT0dTX1MzX0JVQ0tFVH0vJHtMT0dTX1MzX0ZPTERFUn0vJHtMT0dfRklMRX0uZ3ogLi8ke0xPR19GSUxFfS5neiAtLXF1aWV0CgojIFVuemlwIHRoZSBsb2cgZmlsZSwgaWYgdGhlcmUgd2FzIG9uZSBzdG9yZWQgb24gUzMgZm9yIHRvZGF5LgppZiBbIC1mIC4vJHtMT0dfRklMRX0uZ3ogXTsgdGhlbgogIGd1bnppcCAuLyR7TE9HX0ZJTEV9CmZpCgojIElmIHRoZXJlIGlzIG5vIGxvZyBmaWxlIGZvciB0b2RheSwgY3JlYXRlIG9uZS4KaWYgWyAhIC1mIC4vJHtMT0dfRklMRX0gXTsgdGhlbgogIHRvdWNoIC4vJHtMT0dfRklMRX0KZmkKCiMgRmlsdGVyIG91dCBsb2cgZW50cmllcyBmb3IgdG9kYXkuCmNhdCAvdmFyL2xvZy9hY2Nlc3MubG9nIHwgZ3JlcCAkKGRhdGUgKyVkLyViLyVZOikgPiAuL3RvZGF5LmxvZwoKIyBHZXQgdGhlIG5ldyBsb2cgZW50cmllcy4KZGlmZiAtLWNoYW5nZWQtZ3JvdXAtZm9ybWF0PSclPicgLS11bmNoYW5nZWQtZ3JvdXAtZm9ybWF0PScnICRMT0dfRklMRSB0b2RheS5sb2cgPiBuZXcubG9nCgojIEFwcGVuZCB0aGUgbmV3IGxvZyBlbnRyaWVzIHRvIHRoZSBsb2cgZmlsZSBmb3IgdG9kYXkuCmNhdCBuZXcubG9nID4+ICRMT0dfRklMRQoKIyBDb21wcmVzcyB0aGUgdXBkYXRlZCBsb2cgZmlsZS4KZ3ppcCAuLyR7TE9HX0ZJTEV9CgojIENvcHkgdGhlIHVwZGF0ZWQsIGNvbXByZXNzZWQgbG9nIGZpbGUgYmFjayB0byBTMy4KYXdzIHMzIGNwIC4vJHtMT0dfRklMRX0uZ3ogczM6Ly8ke0xPR1NfUzNfQlVDS0VUfS8ke0xPR1NfUzNfRk9MREVSfS8ke0xPR19GSUxFfS5neiAtLXF1aWV0CgojIENsZWFuIHVwLgpybSB0b2RheS5sb2cgbmV3LmxvZyAke0xPR19GSUxFfS5nego=" | base64 -d - > bin/upload_logs_to_s3.sh

  mounts:
    tmp:
      source: local
      source_path: tmp

  disk: 1024

  size: S
  resources:
    base_memory: 768
    memory_ratio: 512
    # Memory allocation: 768 + (0.5 * 512) = 1024

  crons:
    upload_logs_to_s3:
      # This is run hourly at 54 minutes after the hour, since platform.sh can
      # delay cron runs by up to 300 seconds.
      spec: '54 * * * *'
      cmd: |
        if [ "$PLATFORM_BRANCH" = master ]; then
          bash bin/upload_logs_to_s3.sh
        fi
