"https://{default}/":
  type: redirect
  to: https://www.{default}/

"https://www.{default}/":
  type: upstream
  upstream: "varnish:http"
  cache:
    enabled: false
  redirects:
    expires: 300s
    paths:
      '^/(sites/(default|ilr\.cornell\.edu)/files/.*\.pdf)$':
        to: 'https://archive.{default}/download-lookup?path=$1'
        regexp: true
      '/about-ilr/faculty-and-staff-resources':
        to: 'https://{default}/faculty-and-staff-resources'
        code: 301
      '/student-experience':
        to: 'https://{default}/current-students'
        code: 301
      '/institute-workplace-studies':
        to: 'https://{default}/faculty-and-research/centers-and-institutes'
        code: 301
        append_suffix: false
      '/faculty-and-staff-resources/technology-services':
        to: 'https://tdx.cornell.edu/TDClient/82/Portal/Home/'
        code: 301
        append_suffix: false
      '/faculty-and-staff-resources':
        to: 'https://{default}/faculty-staff-resources'
        code: 301
        append_suffix: false
      '/scheinman/roster-neutrals':
        to: 'https://{default}/scheinman-institute/roster-neutrals'
        code: 301
        append_suffix: false
      '/conference-center':
        to: 'https://{default}/nyc-conference-center'
        code: 301
        append_suffix: false

# On 2020-04-15 our internal `d8` subdomain was accidentally shared. So it is
# now a redirect and a new `d8-edit` subdomain has been added.
"https://d8.{default}/":
  type: redirect
  to: https://www.{default}/

# In Summer 2025 we swapped the proxy to default to drupal-latest, so this
# subhost is retired.
"https://d8-edit.{default}/":
  type: redirect
  to: https://www.{default}/

"https://execed.{default}/":
  type: upstream
  upstream: "drupal8:http"
  cache:
    enabled: false

"https://archive.{default}/":
  type: upstream
  upstream: varnish:http
  cache:
    enabled: false

# Summer debate camp. Further redirects are handled in Drupal.
"https://summerdebatecamp.cornell.edu":
  type: upstream
  upstream: "drupal8:http"
  cache:
    enabled: false
"http://*.summerdebatecamp.cornell.edu/":
  type: redirect
  to: https://summerdebatecamp.cornell.edu/

# Legacy Forensics site. Further redirects are handled in Drupal.
"https://forensics.cornell.edu":
  type: upstream
  upstream: "drupal8:http"
  cache:
    enabled: false
"http://*.forensics.cornell.edu/":
  type: redirect
  to: https://forensics.cornell.edu/

# Legacy speechdebate.cornell.edu site.
"https://speechdebate.cornell.edu":
  type: redirect
  to: https://forensics.cornell.edu/
"http://*.speechdebate.cornell.edu/":
  type: redirect
  to: https://forensics.cornell.edu/

# CAHRS legacy hostname redirects.
"https://cahrs.{default}":
  type: redirect
  to: "https://www.{default}/cahrs"

# YTI legacy hostname redirects.
"https://yti.cornell.edu":
  type: redirect
  to: "https://www.{default}/yti"
"https://www.yti.cornell.edu":
  type: redirect
  to: "https://www.{default}/yti"
