"https://{default}/":
  type: redirect
  to: https://www.{default}/

"https://www.{default}/":
  type: upstream
  upstream: "proxy:http"
  cache:
    enabled: false
  redirects:
    expires: 300s
    paths:
      '^/(sites/(default|ilr\.cornell\.edu)/files/.*\.pdf)$':
        to: 'https://archive.{default}/download-lookup?path=$1'
        regexp: true
      '/student-experience':
        to: 'https://{default}/current-students'
        code: 301
      '/scheinman-institute/roster-neutrals':
        to: 'https://{default}/scheinman/roster-neutrals'
        code: 301

# On 2020-04-15 our internal `d8` subdomain was accidentally shared. So it is
# now a redirect and a new `d8-edit` subdomain has been added.
"https://d8.{default}/":
  type: redirect
  to: https://www.{default}/

"https://d8-edit.{default}/":
  type: upstream
  upstream: "drupal8:http"
  cache:
    enabled: false

"https://execed.{default}/":
  type: upstream
  upstream: "drupal8:http"
  cache:
    enabled: false

"https://archive.{default}/":
  type: upstream
  upstream: proxy:http
  cache:
    enabled: false
