db:
  type: mariadb:10.4
  # 1024 * 15
  disk: 15360
  configuration:
    properties:
      max_allowed_packet: 32
    schemas:
      - main
    endpoints:
      mysql:
        default_schema: main
        privileges:
          main: admin
      reporter:
        privileges:
          main: ro
varnish:
  type: varnish:7.6
  relationships:
    application: 'proxy:http'
  configuration:
    vcl: !include
      type: string
      path: config.vcl
